// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SerialBuild.proto

package com.aim.duty.duty_build_entity.protobuf.serial;

public final class SerialBuild {
  private SerialBuild() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerMagicOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.serial.SerMagic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 magicId = 1;</code>
     */
    int getMagicId();

    /**
     * <code>optional int32 duration = 2;</code>
     */
    int getDuration();

    /**
     * <code>optional int32 value = 3;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.serial.SerMagic}
   */
  public  static final class SerMagic extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.serial.SerMagic)
      SerMagicOrBuilder {
    // Use SerMagic.newBuilder() to construct.
    private SerMagic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerMagic() {
      magicId_ = 0;
      duration_ = 0;
      value_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SerMagic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              magicId_ = input.readInt32();
              break;
            }
            case 16: {

              duration_ = input.readInt32();
              break;
            }
            case 24: {

              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.class, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.Builder.class);
    }

    public static final int MAGICID_FIELD_NUMBER = 1;
    private int magicId_;
    /**
     * <code>optional int32 magicId = 1;</code>
     */
    public int getMagicId() {
      return magicId_;
    }

    public static final int DURATION_FIELD_NUMBER = 2;
    private int duration_;
    /**
     * <code>optional int32 duration = 2;</code>
     */
    public int getDuration() {
      return duration_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private int value_;
    /**
     * <code>optional int32 value = 3;</code>
     */
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (magicId_ != 0) {
        output.writeInt32(1, magicId_);
      }
      if (duration_ != 0) {
        output.writeInt32(2, duration_);
      }
      if (value_ != 0) {
        output.writeInt32(3, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (magicId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, magicId_);
      }
      if (duration_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, duration_);
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic other = (com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic) obj;

      boolean result = true;
      result = result && (getMagicId()
          == other.getMagicId());
      result = result && (getDuration()
          == other.getDuration());
      result = result && (getValue()
          == other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MAGICID_FIELD_NUMBER;
      hash = (53 * hash) + getMagicId();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.serial.SerMagic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.serial.SerMagic)
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.class, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        magicId_ = 0;

        duration_ = 0;

        value_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic build() {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic result = new com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic(this);
        result.magicId_ = magicId_;
        result.duration_ = duration_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.getDefaultInstance()) return this;
        if (other.getMagicId() != 0) {
          setMagicId(other.getMagicId());
        }
        if (other.getDuration() != 0) {
          setDuration(other.getDuration());
        }
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int magicId_ ;
      /**
       * <code>optional int32 magicId = 1;</code>
       */
      public int getMagicId() {
        return magicId_;
      }
      /**
       * <code>optional int32 magicId = 1;</code>
       */
      public Builder setMagicId(int value) {
        
        magicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 magicId = 1;</code>
       */
      public Builder clearMagicId() {
        
        magicId_ = 0;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional int32 duration = 2;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional int32 duration = 2;</code>
       */
      public Builder setDuration(int value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 duration = 2;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>optional int32 value = 3;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 3;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.serial.SerMagic)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.serial.SerMagic)
    private static final com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic();
    }

    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerMagic>
        PARSER = new com.google.protobuf.AbstractParser<SerMagic>() {
      public SerMagic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SerMagic(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerMagic> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerMagic> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SerBrickOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.serial.SerBrick)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 mineId = 1;</code>
     */
    int getMineId();

    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */
    int getMagicsCount();
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */
    boolean containsMagics(
        int key);
    /**
     * Use {@link #getMagicsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
    getMagics();
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */
    java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
    getMagicsMap();
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrDefault(
        int key,
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic defaultValue);
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.serial.SerBrick}
   */
  public  static final class SerBrick extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.serial.SerBrick)
      SerBrickOrBuilder {
    // Use SerBrick.newBuilder() to construct.
    private SerBrick(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerBrick() {
      mineId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SerBrick(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              mineId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                magics_ = com.google.protobuf.MapField.newMapField(
                    MagicsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
              magics = input.readMessage(
                  MagicsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              magics_.getMutableMap().put(magics.getKey(), magics.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMagics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.class, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.Builder.class);
    }

    private int bitField0_;
    public static final int MINEID_FIELD_NUMBER = 1;
    private int mineId_;
    /**
     * <code>optional int32 mineId = 1;</code>
     */
    public int getMineId() {
      return mineId_;
    }

    public static final int MAGICS_FIELD_NUMBER = 2;
    private static final class MagicsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>newDefaultInstance(
                  com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> magics_;
    private com.google.protobuf.MapField<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
    internalGetMagics() {
      if (magics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MagicsDefaultEntryHolder.defaultEntry);
      }
      return magics_;
    }

    public int getMagicsCount() {
      return internalGetMagics().getMap().size();
    }
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    public boolean containsMagics(
        int key) {
      
      return internalGetMagics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMagicsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> getMagics() {
      return getMagicsMap();
    }
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    public java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> getMagicsMap() {
      return internalGetMagics().getMap();
    }
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrDefault(
        int key,
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic defaultValue) {
      
      java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> map =
          internalGetMagics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
     */

    public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> map =
          internalGetMagics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mineId_ != 0) {
        output.writeInt32(1, mineId_);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> entry
           : internalGetMagics().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
        magics = MagicsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, magics);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mineId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mineId_);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> entry
           : internalGetMagics().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
        magics = MagicsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, magics);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick other = (com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick) obj;

      boolean result = true;
      result = result && (getMineId()
          == other.getMineId());
      result = result && internalGetMagics().equals(
          other.internalGetMagics());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MINEID_FIELD_NUMBER;
      hash = (53 * hash) + getMineId();
      if (!internalGetMagics().getMap().isEmpty()) {
        hash = (37 * hash) + MAGICS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMagics().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.serial.SerBrick}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.serial.SerBrick)
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMagics();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMagics();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.class, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mineId_ = 0;

        internalGetMutableMagics().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick build() {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick result = new com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.mineId_ = mineId_;
        result.magics_ = internalGetMagics();
        result.magics_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick.getDefaultInstance()) return this;
        if (other.getMineId() != 0) {
          setMineId(other.getMineId());
        }
        internalGetMutableMagics().mergeFrom(
            other.internalGetMagics());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mineId_ ;
      /**
       * <code>optional int32 mineId = 1;</code>
       */
      public int getMineId() {
        return mineId_;
      }
      /**
       * <code>optional int32 mineId = 1;</code>
       */
      public Builder setMineId(int value) {
        
        mineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mineId = 1;</code>
       */
      public Builder clearMineId() {
        
        mineId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> magics_;
      private com.google.protobuf.MapField<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
      internalGetMagics() {
        if (magics_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MagicsDefaultEntryHolder.defaultEntry);
        }
        return magics_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
      internalGetMutableMagics() {
        onChanged();;
        if (magics_ == null) {
          magics_ = com.google.protobuf.MapField.newMapField(
              MagicsDefaultEntryHolder.defaultEntry);
        }
        if (!magics_.isMutable()) {
          magics_ = magics_.copy();
        }
        return magics_;
      }

      public int getMagicsCount() {
        return internalGetMagics().getMap().size();
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public boolean containsMagics(
          int key) {
        
        return internalGetMagics().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMagicsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> getMagics() {
        return getMagicsMap();
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> getMagicsMap() {
        return internalGetMagics().getMap();
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrDefault(
          int key,
          com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic defaultValue) {
        
        java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> map =
            internalGetMagics().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic getMagicsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> map =
            internalGetMagics().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMagics() {
        getMutableMagics().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public Builder removeMagics(
          int key) {
        
        getMutableMagics().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic>
      getMutableMagics() {
        return internalGetMutableMagics().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */
      public Builder putMagics(
          int key,
          com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableMagics().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .com.aim.duty.duty_build_entity.protobuf.serial.SerMagic&gt; magics = 2;</code>
       */

      public Builder putAllMagics(
          java.util.Map<java.lang.Integer, com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerMagic> values) {
        getMutableMagics().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.serial.SerBrick)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.serial.SerBrick)
    private static final com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick();
    }

    public static com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerBrick>
        PARSER = new com.google.protobuf.AbstractParser<SerBrick>() {
      public SerBrick parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SerBrick(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerBrick> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerBrick> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.serial.SerialBuild.SerBrick getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SerialBuild.proto\022.com.aim.duty.duty_b" +
      "uild_entity.protobuf.serial\"<\n\010SerMagic\022" +
      "\017\n\007magicId\030\001 \001(\005\022\020\n\010duration\030\002 \001(\005\022\r\n\005va" +
      "lue\030\003 \001(\005\"\331\001\n\010SerBrick\022\016\n\006mineId\030\001 \001(\005\022T" +
      "\n\006magics\030\002 \003(\0132D.com.aim.duty.duty_build" +
      "_entity.protobuf.serial.SerBrick.MagicsE" +
      "ntry\032g\n\013MagicsEntry\022\013\n\003key\030\001 \001(\005\022G\n\005valu" +
      "e\030\002 \001(\01328.com.aim.duty.duty_build_entity" +
      ".protobuf.serial.SerMagic:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerMagic_descriptor,
        new java.lang.String[] { "MagicId", "Duration", "Value", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor,
        new java.lang.String[] { "MineId", "Magics", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_descriptor =
      internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_descriptor.getNestedTypes().get(0);
    internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_serial_SerBrick_MagicsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
