// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trade.proto

package com.aim.duty.duty_build_entity.protobuf.protocal;

public final class Trade {
  private Trade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CS_SalePropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 propId = 1;</code>
     */
    int getPropId();

    /**
     * <code>optional int32 num = 2;</code>
     */
    int getNum();

    /**
     * <code>optional int32 singlePrice = 3;</code>
     */
    int getSinglePrice();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp}
   */
  public  static final class CS_SaleProp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp)
      CS_SalePropOrBuilder {
    // Use CS_SaleProp.newBuilder() to construct.
    private CS_SaleProp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_SaleProp() {
      propId_ = 0;
      num_ = 0;
      singlePrice_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CS_SaleProp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              propId_ = input.readInt32();
              break;
            }
            case 16: {

              num_ = input.readInt32();
              break;
            }
            case 24: {

              singlePrice_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.Builder.class);
    }

    public static final int PROPID_FIELD_NUMBER = 1;
    private int propId_;
    /**
     * <code>optional int32 propId = 1;</code>
     */
    public int getPropId() {
      return propId_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>optional int32 num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int SINGLEPRICE_FIELD_NUMBER = 3;
    private int singlePrice_;
    /**
     * <code>optional int32 singlePrice = 3;</code>
     */
    public int getSinglePrice() {
      return singlePrice_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (propId_ != 0) {
        output.writeInt32(1, propId_);
      }
      if (num_ != 0) {
        output.writeInt32(2, num_);
      }
      if (singlePrice_ != 0) {
        output.writeInt32(3, singlePrice_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (propId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, propId_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (singlePrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, singlePrice_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp other = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp) obj;

      boolean result = true;
      result = result && (getPropId()
          == other.getPropId());
      result = result && (getNum()
          == other.getNum());
      result = result && (getSinglePrice()
          == other.getSinglePrice());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PROPID_FIELD_NUMBER;
      hash = (53 * hash) + getPropId();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + SINGLEPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getSinglePrice();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp)
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SalePropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        propId_ = 0;

        num_ = 0;

        singlePrice_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp build() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp result = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp(this);
        result.propId_ = propId_;
        result.num_ = num_;
        result.singlePrice_ = singlePrice_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp.getDefaultInstance()) return this;
        if (other.getPropId() != 0) {
          setPropId(other.getPropId());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (other.getSinglePrice() != 0) {
          setSinglePrice(other.getSinglePrice());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int propId_ ;
      /**
       * <code>optional int32 propId = 1;</code>
       */
      public int getPropId() {
        return propId_;
      }
      /**
       * <code>optional int32 propId = 1;</code>
       */
      public Builder setPropId(int value) {
        
        propId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 propId = 1;</code>
       */
      public Builder clearPropId() {
        
        propId_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 2;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 2;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private int singlePrice_ ;
      /**
       * <code>optional int32 singlePrice = 3;</code>
       */
      public int getSinglePrice() {
        return singlePrice_;
      }
      /**
       * <code>optional int32 singlePrice = 3;</code>
       */
      public Builder setSinglePrice(int value) {
        
        singlePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 singlePrice = 3;</code>
       */
      public Builder clearSinglePrice() {
        
        singlePrice_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.protocal.CS_SaleProp)
    private static final com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp();
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_SaleProp>
        PARSER = new com.google.protobuf.AbstractParser<CS_SaleProp>() {
      public CS_SaleProp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CS_SaleProp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_SaleProp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_SaleProp> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_SalePropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 success = 1;</code>
     */
    int getSuccess();

    /**
     * <code>optional int32 propId = 2;</code>
     */
    int getPropId();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp}
   */
  public  static final class SC_SaleProp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp)
      SC_SalePropOrBuilder {
    // Use SC_SaleProp.newBuilder() to construct.
    private SC_SaleProp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_SaleProp() {
      success_ = 0;
      propId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SC_SaleProp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readInt32();
              break;
            }
            case 16: {

              propId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private int success_;
    /**
     * <code>optional int32 success = 1;</code>
     */
    public int getSuccess() {
      return success_;
    }

    public static final int PROPID_FIELD_NUMBER = 2;
    private int propId_;
    /**
     * <code>optional int32 propId = 2;</code>
     */
    public int getPropId() {
      return propId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != 0) {
        output.writeInt32(1, success_);
      }
      if (propId_ != 0) {
        output.writeInt32(2, propId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, success_);
      }
      if (propId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, propId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp other = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (getPropId()
          == other.getPropId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccess();
      hash = (37 * hash) + PROPID_FIELD_NUMBER;
      hash = (53 * hash) + getPropId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp)
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SalePropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = 0;

        propId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp build() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp result = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp(this);
        result.success_ = success_;
        result.propId_ = propId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp.getDefaultInstance()) return this;
        if (other.getSuccess() != 0) {
          setSuccess(other.getSuccess());
        }
        if (other.getPropId() != 0) {
          setPropId(other.getPropId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int success_ ;
      /**
       * <code>optional int32 success = 1;</code>
       */
      public int getSuccess() {
        return success_;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder setSuccess(int value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = 0;
        onChanged();
        return this;
      }

      private int propId_ ;
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public int getPropId() {
        return propId_;
      }
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public Builder setPropId(int value) {
        
        propId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public Builder clearPropId() {
        
        propId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.protocal.SC_SaleProp)
    private static final com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp();
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_SaleProp>
        PARSER = new com.google.protobuf.AbstractParser<SC_SaleProp>() {
      public SC_SaleProp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SC_SaleProp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_SaleProp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_SaleProp> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CS_BuyPropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 commodityId = 1;</code>
     */
    int getCommodityId();

    /**
     * <code>optional int32 num = 2;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp}
   */
  public  static final class CS_BuyProp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp)
      CS_BuyPropOrBuilder {
    // Use CS_BuyProp.newBuilder() to construct.
    private CS_BuyProp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_BuyProp() {
      commodityId_ = 0;
      num_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CS_BuyProp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              commodityId_ = input.readInt32();
              break;
            }
            case 16: {

              num_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.Builder.class);
    }

    public static final int COMMODITYID_FIELD_NUMBER = 1;
    private int commodityId_;
    /**
     * <code>optional int32 commodityId = 1;</code>
     */
    public int getCommodityId() {
      return commodityId_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>optional int32 num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commodityId_ != 0) {
        output.writeInt32(1, commodityId_);
      }
      if (num_ != 0) {
        output.writeInt32(2, num_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commodityId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commodityId_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp other = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp) obj;

      boolean result = true;
      result = result && (getCommodityId()
          == other.getCommodityId());
      result = result && (getNum()
          == other.getNum());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COMMODITYID_FIELD_NUMBER;
      hash = (53 * hash) + getCommodityId();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp)
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyPropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commodityId_ = 0;

        num_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp build() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp result = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp(this);
        result.commodityId_ = commodityId_;
        result.num_ = num_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp.getDefaultInstance()) return this;
        if (other.getCommodityId() != 0) {
          setCommodityId(other.getCommodityId());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commodityId_ ;
      /**
       * <code>optional int32 commodityId = 1;</code>
       */
      public int getCommodityId() {
        return commodityId_;
      }
      /**
       * <code>optional int32 commodityId = 1;</code>
       */
      public Builder setCommodityId(int value) {
        
        commodityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 commodityId = 1;</code>
       */
      public Builder clearCommodityId() {
        
        commodityId_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 2;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 2;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.protocal.CS_BuyProp)
    private static final com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp();
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_BuyProp>
        PARSER = new com.google.protobuf.AbstractParser<CS_BuyProp>() {
      public CS_BuyProp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CS_BuyProp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_BuyProp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_BuyProp> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_BuyPropOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 success = 1;</code>
     */
    int getSuccess();

    /**
     * <code>optional int32 propId = 2;</code>
     */
    int getPropId();

    /**
     * <code>optional int32 propType = 3;</code>
     */
    int getPropType();

    /**
     * <code>optional bytes abstractProp = 4;</code>
     */
    com.google.protobuf.ByteString getAbstractProp();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp}
   */
  public  static final class SC_BuyProp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp)
      SC_BuyPropOrBuilder {
    // Use SC_BuyProp.newBuilder() to construct.
    private SC_BuyProp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_BuyProp() {
      success_ = 0;
      propId_ = 0;
      propType_ = 0;
      abstractProp_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SC_BuyProp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readInt32();
              break;
            }
            case 16: {

              propId_ = input.readInt32();
              break;
            }
            case 24: {

              propType_ = input.readInt32();
              break;
            }
            case 34: {

              abstractProp_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private int success_;
    /**
     * <code>optional int32 success = 1;</code>
     */
    public int getSuccess() {
      return success_;
    }

    public static final int PROPID_FIELD_NUMBER = 2;
    private int propId_;
    /**
     * <code>optional int32 propId = 2;</code>
     */
    public int getPropId() {
      return propId_;
    }

    public static final int PROPTYPE_FIELD_NUMBER = 3;
    private int propType_;
    /**
     * <code>optional int32 propType = 3;</code>
     */
    public int getPropType() {
      return propType_;
    }

    public static final int ABSTRACTPROP_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString abstractProp_;
    /**
     * <code>optional bytes abstractProp = 4;</code>
     */
    public com.google.protobuf.ByteString getAbstractProp() {
      return abstractProp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != 0) {
        output.writeInt32(1, success_);
      }
      if (propId_ != 0) {
        output.writeInt32(2, propId_);
      }
      if (propType_ != 0) {
        output.writeInt32(3, propType_);
      }
      if (!abstractProp_.isEmpty()) {
        output.writeBytes(4, abstractProp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, success_);
      }
      if (propId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, propId_);
      }
      if (propType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, propType_);
      }
      if (!abstractProp_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, abstractProp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp other = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (getPropId()
          == other.getPropId());
      result = result && (getPropType()
          == other.getPropType());
      result = result && getAbstractProp()
          .equals(other.getAbstractProp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccess();
      hash = (37 * hash) + PROPID_FIELD_NUMBER;
      hash = (53 * hash) + getPropId();
      hash = (37 * hash) + PROPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPropType();
      hash = (37 * hash) + ABSTRACTPROP_FIELD_NUMBER;
      hash = (53 * hash) + getAbstractProp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp)
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyPropOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.class, com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.Builder.class);
      }

      // Construct using com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = 0;

        propId_ = 0;

        propType_ = 0;

        abstractProp_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp getDefaultInstanceForType() {
        return com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.getDefaultInstance();
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp build() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp buildPartial() {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp result = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp(this);
        result.success_ = success_;
        result.propId_ = propId_;
        result.propType_ = propType_;
        result.abstractProp_ = abstractProp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp) {
          return mergeFrom((com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp other) {
        if (other == com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp.getDefaultInstance()) return this;
        if (other.getSuccess() != 0) {
          setSuccess(other.getSuccess());
        }
        if (other.getPropId() != 0) {
          setPropId(other.getPropId());
        }
        if (other.getPropType() != 0) {
          setPropType(other.getPropType());
        }
        if (other.getAbstractProp() != com.google.protobuf.ByteString.EMPTY) {
          setAbstractProp(other.getAbstractProp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int success_ ;
      /**
       * <code>optional int32 success = 1;</code>
       */
      public int getSuccess() {
        return success_;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder setSuccess(int value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = 0;
        onChanged();
        return this;
      }

      private int propId_ ;
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public int getPropId() {
        return propId_;
      }
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public Builder setPropId(int value) {
        
        propId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 propId = 2;</code>
       */
      public Builder clearPropId() {
        
        propId_ = 0;
        onChanged();
        return this;
      }

      private int propType_ ;
      /**
       * <code>optional int32 propType = 3;</code>
       */
      public int getPropType() {
        return propType_;
      }
      /**
       * <code>optional int32 propType = 3;</code>
       */
      public Builder setPropType(int value) {
        
        propType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 propType = 3;</code>
       */
      public Builder clearPropType() {
        
        propType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString abstractProp_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes abstractProp = 4;</code>
       */
      public com.google.protobuf.ByteString getAbstractProp() {
        return abstractProp_;
      }
      /**
       * <code>optional bytes abstractProp = 4;</code>
       */
      public Builder setAbstractProp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        abstractProp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes abstractProp = 4;</code>
       */
      public Builder clearAbstractProp() {
        
        abstractProp_ = getDefaultInstance().getAbstractProp();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build_entity.protobuf.protocal.SC_BuyProp)
    private static final com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp();
    }

    public static com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_BuyProp>
        PARSER = new com.google.protobuf.AbstractParser<SC_BuyProp>() {
      public SC_BuyProp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SC_BuyProp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_BuyProp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_BuyProp> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Trade.proto\0220com.aim.duty.duty_build_e" +
      "ntity.protobuf.protocal\"?\n\013CS_SaleProp\022\016" +
      "\n\006propId\030\001 \001(\005\022\013\n\003num\030\002 \001(\005\022\023\n\013singlePri" +
      "ce\030\003 \001(\005\".\n\013SC_SaleProp\022\017\n\007success\030\001 \001(\005" +
      "\022\016\n\006propId\030\002 \001(\005\".\n\nCS_BuyProp\022\023\n\013commod" +
      "ityId\030\001 \001(\005\022\013\n\003num\030\002 \001(\005\"U\n\nSC_BuyProp\022\017" +
      "\n\007success\030\001 \001(\005\022\016\n\006propId\030\002 \001(\005\022\020\n\010propT" +
      "ype\030\003 \001(\005\022\024\n\014abstractProp\030\004 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_SaleProp_descriptor,
        new java.lang.String[] { "PropId", "Num", "SinglePrice", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_SaleProp_descriptor,
        new java.lang.String[] { "Success", "PropId", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_BuyProp_descriptor,
        new java.lang.String[] { "CommodityId", "Num", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_BuyProp_descriptor,
        new java.lang.String[] { "Success", "PropId", "PropType", "AbstractProp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
